[[redirects]]
  from = "https://io-oi.netlify.com/*"
  to = "https://io-oi.me/:splat"
  force = true
[[redirects]]
  from = "/technology/computer/computer-aided-art/2017/06/09/hexo-next-optimization.html"
  to = "/tech/hexo-next-optimization.html"
[[redirects]]
  from = "/technology/internet/zeronet/2017/09/01/first-exploration-of-the-zeronet.html"
  to = "/tech/first-exploration-of-the-zeronet.html"
[[redirects]]
  from = "/technology/computer/system-software/2018/12/11/hello-arch-linux.html"
  to = "/tech/hello-arch-linux.html"
[[redirects]]
  from = "/technology/computer/computer-aided-art/2018/05/30/speed-up-hexo.html"
  to = "/tech/speed-up-hexo.html"
[[redirects]]
  from = "/technology/computer/computer-aided-art/2018/07/18/custom-domains-on-github-pages.html"
  to = "/tech/custom-domains-on-github-pages.html"
[[redirects]]
  from = "/beautiful/share/2018/12/11/noto-serif-sc-added-on-google-fonts.html"
  to = "/tech/noto-serif-sc-added-on-google-fonts.html"
[[redirects]]
  from = "/the-philosophy-of-web-typography/text-indent-or-margin.html"
  to = "/tech/the-philosophy-of-web-typography-text-indent-or-margin.html"
